name: batchlogit
channels:
  - rapidsai-nightly
  - nvidia 
  - pytorch 
  - conda-forge 
  - defaults
dependencies:
  - python>=3.8,<4.0
  - pytorch==1.8.0
  - click>=7.1.2,<8.0.0
  - scikit-learn>=0.24.1,<0.25.0
  - more-itertools>=8.6.0,<9.0.0
  - conda-forge::click-log>=0.3.2,<0.4.0
  - conda-forge::loky>=2.9.0,<3.0.0
  - cudatoolkit=10.2
  - cuml=0.19
